const PropertyMessage = {
    price: "Price",
    garage: "Garage",
    location: 'Location',
    bedrooms: "Bedrooms",
    bathrooms: "Bathrooms",
    square_feet: "Square feet",
    enter_price:'Enter price',
    enter_garage: "Enter garage",
    enter_garage: "Enter garage",
    edit_property: 'Edit property',
    enter_location:'Enter location',
    enter_bedrooms: "Enter bedrooms",
    propertyRealtor: "Property realtor",
    price_required: "Price is required",
    property_realtor: "Property Realtor",
    enter_bathrooms: "Enter bathrooms",
    propert_details: "Property details",
    enter_square_feet:'Enter square feet',
    add_a_new_property: 'Add a new property',
    select_property_realtor: "Select property realtor",
    propertyRealtor_required: "Property realtor is required",
    delete_property_message: 'Are you sure you want to delete this property?',
    property_realtor_mobile_number: "Property realtor mobile number"
}
export default PropertyMessage;