const CommonMessage = {
    add: 'Add',
    name:'Name',
    role: 'Role',
    edit: 'Edit',
    action: 'Action',
    delete: 'Delete',
    submit: 'Submit',
    cancel:'Cancel',
    update: 'Update',
    danger: 'danger',
    success: 'success',
    edit_role: 'Edit role',
    enter_name: 'Enter name',
    created_at: 'Created At',
    select_role: 'Select role',
    no_data_found: "No data found",
    name_required: 'Name is required',
    add_a_new_role: 'Add a new role',
    delete_role_message: 'Are you sure you want to delete this role?',
    name_more_than_characters: "Name must be more than 3 characters",
    users: "Users",
    properties: "Properties"
}
export default CommonMessage;